<?php

/**
 * @file
 * This is the Sitemeta module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * {@inheritdoc}
 */
function sitemeta_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sitemeta':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Site Meta module provides a flexible and easy method to set meta tags, such as page title, description and keywords for pages.') . '</p>';
  }
  return $output;
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Alters the page title if we have sitemeta entry for current page.
 */
function sitemeta_preprocess_html(&$vars) {
  $current_path = \Drupal::service('path.current')->getPath();
  $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();

  if ($sitemeta = \Drupal::service('sitemeta.sitemeta.generator')->getSiteMeta($current_path, $current_language)) {
    if ($sitemeta->getName()) {
      unset($vars['head_title']['name']);
      $vars['head_title']['title'] = $sitemeta->getName();
    }
  }
}
