<?php

/**
 * @file
 * This is the Sitemeta module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * {@inheritdoc}
 */
function sitemeta_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sitemeta':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Site Meta module provides a flexible and easy method to set meta tags, such as page title, description and keywords for pages.') . '</p>';
  }
  return $output;
}
